WIP feat(centos-8): added centos 8 support
saltstack-formulas/packages-formula pull request #72
Opened 2021-01-22 19:58 UTC by aboe76

moved RedHat/CentOS to osmap and osfingermap to accomodate changes in
package provider versionlock

Do not merge yet, waiting on salt bug: saltstack/salt#54798
Centos 8 uses the wrong package provider, should be dnf but it's using yum
which results in an error with yum-plugin-versionlock, which isn't available on centos-8.

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

### Describe the changes you're proposing

### Pillar / config required to test the proposed changes

### Debug log showing how the proposed changes work

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

2021-01-22 20:09 UTC, myii commented
Thanks for re-opening this @aboe76.  The PR title will be perfect as the commit message, so that will allow the tests to run.

```diff
-Add centos 8 to osfingermap
+feat(centos-8): added centos 8 support
```

The commit body can stay the same, that shouldn't cause a problem.

2021-01-23 15:08 UTC, myii commented
@aboe76 Thanks for updating this.  Unfortunately, we haven't enabled any of the `centos-8` images for testing yet!  I'll try that right now in my fork and let you know what the results are.

2021-01-23 15:23 UTC, myii commented
@aboe76 OK, we've got a few failing states (`Succeeded: 13 (changed=5); Failed:     8`) for all of the instances:

* https://gitlab.com/myii/packages-formula/-/pipelines/245878109

Would you mind enabling `centos-centos-8-master-py3` in this PR so that we can resolve there failures as well?

2021-01-23 20:36 UTC, myii commented
Hmm, the CI run for the very last commit (572665a) isn't showing up here but it was pushed through to GitLab, it seems:

* https://gitlab.com/saltstack-formulas/packages-formula/-/pipelines/245925810
  - Unfortunately, both `centos-7` and `centos-8` are failing.

This is the first time this has happened, so I'll ask the `coqbot` team about this.

2021-01-23 20:41 UTC, myii commented
Sent a question to them: https://coq.zulipchat.com/#narrow/stream/243318-coqbot-devs.20.26.20users/topic/GitHub.20reporting.20failing.20after.20numerous.20pushes.20to.20a.20PR/near/223774255.

2021-01-23 21:24 UTC, aboe76 commented
strange, it has to do with 'yum-plugin-versionlock' but I need to specify this for the following machines:
RedHat/Centos 6/7 : yum-plugin-versionlock
RedHat/Centos 8: dnf-plugin-versionlock

So that's why there is a osfingermap file, but I need to know what the RedHat osfinger looks like to complete it.

2021-01-23 21:28 UTC, myii commented
@aboe76 Strange, the GitLab report is showing up now.  Did you do anything?

Anyway, the issue seems to be with the test pillar file: https://github.com/saltstack-formulas/packages-formula/blob/f893e2af43bf547d64cbbb3b06c27bef767c65ff/test/salt/pillar/redhat.sls#L17-L20.

Probably can remove both of those, so that they don't interfere with the `pkgs:required:pkgs` defined in the `os*.yaml` files.

The other failure seems to be with the `held` packages.

2021-01-23 22:08 UTC, aboe76 commented
> @aboe76 Strange, the GitLab report is showing up now. Did you do anything?
> 
> Anyway, the issue seems to be with the test pillar file:
> 
> https://github.com/saltstack-formulas/packages-formula/blob/f893e2af43bf547d64cbbb3b06c27bef767c65ff/test/salt/pillar/redhat.sls#L17-L20
> 
> .
> Probably can remove both of those, so that they don't interfere with the `pkgs:required:pkgs` defined in the `os*.yaml` files.
> 
> The other failure seems to be with the `held` packages.

Let's test

2021-02-04 07:43 UTC, Yoda-BZH commented
Hello,

Any news ?

Thank you !

2021-02-04 10:14 UTC, aboe76 commented
I still have issues, in the pipeline testing with one single pillar on "redhat" machines...

2021-02-07 17:00 UTC, aboe76 commented
@myii can you take a look why centos8 takes so long?

2021-02-07 17:51 UTC, myii commented
> @myii can you take a look why centos8 takes so long?

@aboe76 It appeared to have been cancelled so I restarted it and now it's all working except one of the tests:

* https://gitlab.com/saltstack-formulas/packages-formula/-/jobs/1013667577

The problem is here:

```rb
# Prepare platform "finger"
platform_finger = platform[:finger].split('.').first.to_s
```

There isn't a `platform[:finger]` provided by InSpec.  We've actually got a shared library available that provides that and then you use:

```diff
-platform_finger = platform[:finger].split('.').first.to_s
+platform_finger = system.platform[:finger].split('.').first.to_s
```

So you'll need to copy this entire directory over from the `template-formula` as well:

* https://github.com/saltstack-formulas/template-formula/tree/master/test/integration/share

Once that's confirmed working, there are just a couple of other minor issues I'd like to discuss when we rebase this PR.

2021-02-07 22:48 UTC, aboe76 commented
@myii it's working with the 'share' folder

2021-02-07 23:06 UTC, aboe76 commented
this also fixes: #66

2021-02-09 08:36 UTC, myii requested changes
Generally fine, @aboe76 -- just a couple of fixes suggested.

In fact, this commit contains everything, including adding a test run for `oraclelinux-8`:

* https://github.com/myii/packages-formula/commit/d74462a65f4ddfddd62a11abc812dd14ddb595d3

Here's the corresponding CI run:

* https://gitlab.com/myii/packages-formula/-/pipelines/253493343

I'm not sure if I'm able to push that here directly because this PR was sent through from your `master` branch.

2021-02-09 08:36 UTC, myii commented on .gitlab-ci.yml
> +centos8-centos-8-master-py3: {extends: '.test_instance'}
```suggestion
redhat8-centos-8-master-py3: {extends: '.test_instance'}
```

See below.

2021-02-09 08:36 UTC, myii commented on kitchen.yml
> +  - name: centos8
```suggestion
  - name: redhat8
```

Will be required for `oraclelinux-8` as well, so suggest renaming this accordingly (also matches the test pillar name below).

2021-02-09 08:36 UTC, myii commented on packages/osfingermap.yaml
> +CentOS Linux-6:
This is the actual `osfinger` for this platform:

```suggestion
CentOS-6:
```

2021-02-09 19:27 UTC, aboe76 commented
@myii are you happy with RedHat, Centos and Oracle linux 8 support?

2021-02-10 08:35 UTC, myii commented on .gitlab-ci.yml
> +redhat8-oraclelinux-8-master-py3: {extends: '.test_instance'}
This line will end up getting moved lower down in the file once I update the `ssf-formula` with this PR but nothing to worry about (I'll just push the commit on top after this PR is merged).  Just for your info, @aboe76.

2021-02-10 08:36 UTC, myii approved these changes
Nice work, @aboe76!  Thanks for all of the patience it took.

2021-02-10 08:36 UTC, merged

2021-09-06 13:23 UTC, Yoda-BZH commented
Apparently the correction for `Red Hat Enterprise Linux-8` (osfinger) is not complete.

I still have :
```
local:
----------
          ID: pkg_req_pkgs
    Function: pkg.installed
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "The following packages failed to install/update: yum-plugin-versionlock"
              Attempt 2: Returned a result of "False", with the following comment: "The following packages failed to install/update: yum-plugin-versionlock"
              The following packages failed to install/update: yum-plugin-versionlock
     Started: 15:15:05.139721
    Duration: 154690.206 ms
     Changes:   
----------
```

Redhat 8 Enterprise uses dnf, not yum

2021-09-06 13:30 UTC, myii commented
> Apparently the correction for `Red Hat Enterprise Linux-8` (osfinger) is not complete.

@Yoda-BZH Yes, unfortunately we don't have CI testing for that at the moment.  If I recall correctly, the `salt-bootstrap` doesn't complete the installation successfully for it.

Please feel free to submit a PR and we can get that merged pretty quickly.